package pf.api.model;
// Generated Nov 19, 2019, 9:44:38 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="Product"
    ,schema="dbo"
    ,catalog="ScrapingProducts"
    , uniqueConstraints = @UniqueConstraint(columnNames="code") 
)
public class Product  implements java.io.Serializable {


     private Integer id;
     private Serializable name;
     private Serializable code;
     private Set<SourceProduct> sourceProducts = new HashSet<SourceProduct>(0);

    public Product() {
    }

	
    public Product(Integer id) {
        this.id = id;
    }
    public Product(Integer id, Serializable name, Serializable code, Set<SourceProduct> sourceProducts) {
       this.id = id;
       this.name = name;
       this.code = code;
       this.sourceProducts = sourceProducts;
    }
   
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
     
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name")
    public Serializable getName() {
        return this.name;
    }
    
    public void setName(Serializable name) {
        this.name = name;
    }

    
    @Column(name="code", unique=true)
    public Serializable getCode() {
        return this.code;
    }
    
    public void setCode(Serializable code) {
        this.code = code;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<SourceProduct> getSourceProducts() {
        return this.sourceProducts;
    }
    
    public void setSourceProducts(Set<SourceProduct> sourceProducts) {
        this.sourceProducts = sourceProducts;
    }




}


