package pf.api.model;
// Generated Nov 19, 2019, 9:44:38 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SourceProduct generated by hbm2java
 */
@Entity
@Table(name="SourceProduct"
    ,schema="dbo"
    ,catalog="ScrapingProducts"
)
public class SourceProduct  implements java.io.Serializable {


     private SourceProductId id;
     private Product product;
     private Source source;
     private Serializable price;
     private Serializable link;
     private Serializable image;

    public SourceProduct() {
    }

	
    public SourceProduct(SourceProductId id, Product product, Source source) {
        this.id = id;
        this.product = product;
        this.source = source;
    }
    public SourceProduct(SourceProductId id, Product product, Source source, Serializable price, Serializable link, Serializable image) {
       this.id = id;
       this.product = product;
       this.source = source;
       this.price = price;
       this.link = link;
       this.image = image;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="sourceId", column=@Column(name="SourceID", nullable=false) ), 
        @AttributeOverride(name="productId", column=@Column(name="ProductID", nullable=false) ) } )
    public SourceProductId getId() {
        return this.id;
    }
    
    public void setId(SourceProductId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ProductID", nullable=false, insertable=false, updatable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SourceID", nullable=false, insertable=false, updatable=false)
    public Source getSource() {
        return this.source;
    }
    
    public void setSource(Source source) {
        this.source = source;
    }

    
    @Column(name="price")
    public Serializable getPrice() {
        return this.price;
    }
    
    public void setPrice(Serializable price) {
        this.price = price;
    }

    
    @Column(name="link")
    public Serializable getLink() {
        return this.link;
    }
    
    public void setLink(Serializable link) {
        this.link = link;
    }

    
    @Column(name="image")
    public Serializable getImage() {
        return this.image;
    }
    
    public void setImage(Serializable image) {
        this.image = image;
    }




}


