package pf.api.model;
// Generated Nov 19, 2019, 9:44:38 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SourceProductId generated by hbm2java
 */
@Embeddable
public class SourceProductId  implements java.io.Serializable {


     private Integer sourceId;
     private Integer productId;

    public SourceProductId() {
    }

    public SourceProductId(Integer sourceId, Integer productId) {
       this.sourceId = sourceId;
       this.productId = productId;
    }
   


    @Column(name="SourceID", nullable=false)
    public Integer getSourceId() {
        return this.sourceId;
    }
    
    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }


    @Column(name="ProductID", nullable=false)
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SourceProductId) ) return false;
		 SourceProductId castOther = ( SourceProductId ) other; 
         
		 return (this.getSourceId()==castOther.getSourceId())
 && (this.getProductId()==castOther.getProductId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSourceId();
         result = 37 * result + this.getProductId();
         return result;
   }   


}


