package pf.api.model;
// Generated Nov 19, 2019, 9:44:38 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Source generated by hbm2java
 */
@Entity
@Table(name="Source"
    ,schema="dbo"
    ,catalog="ScrapingProducts"
)
public class Source {
    
     private Integer id;
     private String name;
     private String icon;
     private Set<SourceProduct> sourceProducts = new HashSet<SourceProduct>(0);

    public Source() {
    }

	
    public Source(Integer id) {
        this.id = id;
    }
    public Source(Integer id, String name, String icon, Set<SourceProduct> sourceProducts) {
       this.id = id;
       this.name = name;
       this.icon = icon;
       this.sourceProducts = sourceProducts;
    }
   
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
     
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="icon")
    public String getIcon() {
        return this.icon;
    }
    
    public void setIcon(String icon) {
        this.icon = icon;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="source")
    public Set<SourceProduct> getSourceProducts() {
        return this.sourceProducts;
    }
    
    public void setSourceProducts(Set<SourceProduct> sourceProducts) {
        this.sourceProducts = sourceProducts;
    }




}


